import { Bebas_Neue, Archivo } from "next/font/google";
import "./globals.css";

const bebasNeue = Bebas_Neue ({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400"
});

const archivo = Archivo ({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${archivo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
